# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('missionlogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 9, 56, 46, 57673, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 9, 56, 49, 822483, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vessel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 9, 56, 52, 422608, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vessel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 9, 56, 54, 69595, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
