# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionlogger', '0002_auto_20160507_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
