# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionlogger', '0003_mission_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='created_at',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='updated_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='created_at',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
